export interface AttackPattern {
  id: string;
  category: string;
  pattern: RegExp;
  severity: 'critical' | 'high' | 'medium' | 'info';
  description: string;
}

export const INJECTION_PATTERNS: AttackPattern[] = [
  // === JAILBREAK PATTERNS (1-10) ===
  {
    id: 'PI-001',
    category: 'jailbreak',
    pattern: /ignore\s+(all\s+)?(previous|prior|above|earlier)\s+(instructions?|prompts?|rules?|guidelines?)/i,
    severity: 'critical',
    description: 'Direct instruction override: ignore previous instructions',
  },
  {
    id: 'PI-002',
    category: 'jailbreak',
    pattern: /forget\s+(everything|all|your)\s+(you\s+)?(know|were\s+told|instructions?|training)/i,
    severity: 'critical',
    description: 'Memory wipe attempt: forget training/instructions',
  },
  {
    id: 'PI-003',
    category: 'jailbreak',
    pattern: /you\s+are\s+now\s+(DAN|evil|unfiltered|uncensored|jailbroken|free)/i,
    severity: 'critical',
    description: 'DAN/jailbreak persona activation',
  },
  {
    id: 'PI-004',
    category: 'jailbreak',
    pattern: /do\s+anything\s+now|DAN\s+mode|developer\s+mode\s+(enabled|on|activated)/i,
    severity: 'critical',
    description: 'DAN mode or developer mode activation',
  },
  {
    id: 'PI-005',
    category: 'jailbreak',
    pattern: /act\s+as\s+if\s+(you\s+have\s+)?no\s+(restrictions?|limitations?|filters?|safety|guardrails?)/i,
    severity: 'critical',
    description: 'Safety filter bypass attempt',
  },
  {
    id: 'PI-006',
    category: 'jailbreak',
    pattern: /pretend\s+(that\s+)?(you\s+)?(are|can|have)\s+(no|unlimited|unrestricted)/i,
    severity: 'high',
    description: 'Pretend to bypass restrictions',
  },
  {
    id: 'PI-007',
    category: 'jailbreak',
    pattern: /hypothetical(ly)?\s+(scenario|situation|world|universe)\s+(where|in\s+which)/i,
    severity: 'medium',
    description: 'Hypothetical scenario for bypassing safety',
  },
  {
    id: 'PI-008',
    category: 'jailbreak',
    pattern: /for\s+(educational|research|academic|testing)\s+purposes?\s+only/i,
    severity: 'medium',
    description: 'Educational purpose disclaimer as bypass',
  },
  {
    id: 'PI-009',
    category: 'jailbreak',
    pattern: /in\s+a\s+fictional\s+(world|story|context|setting)/i,
    severity: 'medium',
    description: 'Fictional context to bypass restrictions',
  },
  {
    id: 'PI-010',
    category: 'jailbreak',
    pattern: /simulate\s+(being|a)\s+(hacker|attacker|malicious|evil|unrestricted)/i,
    severity: 'high',
    description: 'Simulation of malicious persona',
  },

  // === ROLE SWITCH PATTERNS (11-20) ===
  {
    id: 'PI-011',
    category: 'role-switch',
    pattern: /you\s+are\s+no\s+longer\s+(an?\s+)?(AI|assistant|chatbot|claude|gpt)/i,
    severity: 'critical',
    description: 'Identity override: you are no longer an AI',
  },
  {
    id: 'PI-012',
    category: 'role-switch',
    pattern: /from\s+now\s+on,?\s+(you\s+)?(will|must|should|are)\s+(act|behave|respond|be)/i,
    severity: 'high',
    description: 'Behavioral override: from now on directive',
  },
  {
    id: 'PI-013',
    category: 'role-switch',
    pattern: /new\s+(system\s+)?instructions?:\s*/i,
    severity: 'critical',
    description: 'Injected system instructions',
  },
  {
    id: 'PI-014',
    category: 'role-switch',
    pattern: /\[system\]|\[SYSTEM\]|<system>|<<SYS>>|###\s*system/i,
    severity: 'critical',
    description: 'System prompt delimiter injection',
  },
  {
    id: 'PI-015',
    category: 'role-switch',
    pattern: /override\s+(system|core|base)\s+(prompt|instructions?|config)/i,
    severity: 'critical',
    description: 'System prompt override attempt',
  },
  {
    id: 'PI-016',
    category: 'role-switch',
    pattern: /your\s+(new|updated|real|actual|true)\s+(role|purpose|mission|objective)\s+is/i,
    severity: 'high',
    description: 'Role reassignment attempt',
  },
  {
    id: 'PI-017',
    category: 'role-switch',
    pattern: /switch\s+to\s+(admin|root|developer|debug|maintenance)\s+mode/i,
    severity: 'critical',
    description: 'Privilege escalation via mode switch',
  },
  {
    id: 'PI-018',
    category: 'role-switch',
    pattern: /enable\s+(god|sudo|admin|root|superuser)\s+mode/i,
    severity: 'critical',
    description: 'God/sudo mode activation',
  },
  {
    id: 'PI-019',
    category: 'role-switch',
    pattern: /entering\s+(maintenance|debug|admin|test)\s+mode/i,
    severity: 'high',
    description: 'Maintenance/debug mode claim',
  },
  {
    id: 'PI-020',
    category: 'role-switch',
    pattern: /respond\s+(only\s+)?(in|with|using)\s+(json|xml|code|base64|hex)/i,
    severity: 'medium',
    description: 'Output format manipulation',
  },

  // === INSTRUCTION OVERRIDE (21-30) ===
  {
    id: 'PI-021',
    category: 'instruction-override',
    pattern: /disregard\s+(all\s+)?(previous|prior|above|earlier|your)\s+(previous\s+|prior\s+)?(instructions?|rules?|guidelines?)/i,
    severity: 'critical',
    description: 'Disregard instructions directive',
  },
  {
    id: 'PI-022',
    category: 'instruction-override',
    pattern: /stop\s+(following|obeying|adhering\s+to)\s+(your|the|those|these)\s+(rules?|instructions?|guidelines?)/i,
    severity: 'critical',
    description: 'Stop following rules directive',
  },
  {
    id: 'PI-023',
    category: 'instruction-override',
    pattern: /the\s+(above|previous|prior)\s+(instructions?|rules?|text)\s+(are|were|is)\s+(a\s+)?test/i,
    severity: 'high',
    description: 'Dismiss instructions as test',
  },
  {
    id: 'PI-024',
    category: 'instruction-override',
    pattern: /actual\s+instructions?\s+(begin|start|follow|are\s+below)/i,
    severity: 'critical',
    description: 'Fake "actual instructions" injection',
  },
  {
    id: 'PI-025',
    category: 'instruction-override',
    pattern: /do\s+not\s+(refuse|decline|reject|filter|censor|restrict)/i,
    severity: 'high',
    description: 'Anti-refusal directive',
  },
  {
    id: 'PI-026',
    category: 'instruction-override',
    pattern: /always\s+(comply|obey|agree|say\s+yes|accept)/i,
    severity: 'high',
    description: 'Forced compliance directive',
  },
  {
    id: 'PI-027',
    category: 'instruction-override',
    pattern: /never\s+(refuse|say\s+no|decline|reject|apologize)/i,
    severity: 'high',
    description: 'Never refuse directive',
  },
  {
    id: 'PI-028',
    category: 'instruction-override',
    pattern: /priority\s*:\s*(highest|maximum|override|critical|urgent)/i,
    severity: 'high',
    description: 'Fake priority escalation',
  },
  {
    id: 'PI-029',
    category: 'instruction-override',
    pattern: /this\s+(overrides?|supersedes?|replaces?|takes?\s+precedence)/i,
    severity: 'high',
    description: 'Override precedence claim',
  },
  {
    id: 'PI-030',
    category: 'instruction-override',
    pattern: /IMPORTANT|URGENT|CRITICAL|MANDATORY|OVERRIDE/,
    severity: 'medium',
    description: 'Urgency/importance keywords for override',
  },

  // === DATA EXTRACTION (31-40) ===
  {
    id: 'PI-031',
    category: 'data-extraction',
    pattern: /repeat\s+(your|the)\s+(system\s+)?(prompt|instructions?|rules?|context|configuration)/i,
    severity: 'critical',
    description: 'System prompt extraction: repeat instructions',
  },
  {
    id: 'PI-032',
    category: 'data-extraction',
    pattern: /what\s+(are|were)\s+your\s+(initial|original|system|base)\s+(instructions?|prompt|rules?)/i,
    severity: 'high',
    description: 'System prompt extraction: ask for instructions',
  },
  {
    id: 'PI-033',
    category: 'data-extraction',
    pattern: /show\s+(me\s+)?(your|the)\s+(system|hidden|secret|internal)\s+(prompt|message|instructions?)/i,
    severity: 'critical',
    description: 'Show system prompt request',
  },
  {
    id: 'PI-034',
    category: 'data-extraction',
    pattern: /print\s+(your\s+)?(system\s+)?(prompt|instructions?|configuration|config)/i,
    severity: 'high',
    description: 'Print configuration/prompt request',
  },
  {
    id: 'PI-035',
    category: 'data-extraction',
    pattern: /output\s+(your\s+)?(entire|full|complete|whole)\s+(system\s+)?(prompt|context|instructions?)/i,
    severity: 'critical',
    description: 'Full prompt output request',
  },
  {
    id: 'PI-036',
    category: 'data-extraction',
    pattern: /list\s+(all\s+)?(your\s+)?(tools?|functions?|capabilities|permissions?|api\s+keys?)/i,
    severity: 'high',
    description: 'Tool/capability enumeration',
  },
  {
    id: 'PI-037',
    category: 'data-extraction',
    pattern: /what\s+(tools?|functions?|apis?|endpoints?)\s+(do\s+you\s+have|can\s+you\s+access|are\s+available)/i,
    severity: 'medium',
    description: 'Tool discovery probe',
  },
  {
    id: 'PI-038',
    category: 'data-extraction',
    pattern: /reveal\s+(your|the|any)\s+(secrets?|passwords?|tokens?|keys?|credentials?)/i,
    severity: 'critical',
    description: 'Secret/credential extraction attempt',
  },
  {
    id: 'PI-039',
    category: 'data-extraction',
    pattern: /encode\s+(your\s+)?(system\s+)?(prompt|instructions?|response)\s+(in|as|to)\s+(base64|hex|rot13)/i,
    severity: 'high',
    description: 'Encoded exfiltration attempt',
  },
  {
    id: 'PI-040',
    category: 'data-extraction',
    pattern: /translate\s+(your\s+)?(system\s+)?(prompt|instructions?)\s+(to|into)/i,
    severity: 'medium',
    description: 'Translation-based prompt extraction',
  },

  // === ENCODING/OBFUSCATION (41-45) ===
  {
    id: 'PI-041',
    category: 'encoding',
    pattern: /[\u200B\u200C\u200D\uFEFF\u00AD]{3,}/,
    severity: 'high',
    description: 'Zero-width character obfuscation (3+ chars)',
  },
  {
    id: 'PI-042',
    category: 'encoding',
    pattern: /\\u[0-9a-fA-F]{4}.*\\u[0-9a-fA-F]{4}/,
    severity: 'medium',
    description: 'Unicode escape sequence injection',
  },
  {
    id: 'PI-043',
    category: 'encoding',
    pattern: /&#x?[0-9a-fA-F]+;.*&#x?[0-9a-fA-F]+;/,
    severity: 'medium',
    description: 'HTML entity encoding injection',
  },
  {
    id: 'PI-044',
    category: 'encoding',
    pattern: /%[0-9a-fA-F]{2}.*%[0-9a-fA-F]{2}.*%[0-9a-fA-F]{2}/,
    severity: 'medium',
    description: 'URL encoding injection',
  },
  {
    id: 'PI-045',
    category: 'encoding',
    pattern: /(?<!\bclass\s)\beval\s*\(|(?<!\bclass\s)\bexec\s*\(|(?<!\bclass\s)(?<!\bdef\s)new\s+Function\s*\(/,
    severity: 'critical',
    description: 'Code execution function in prompt',
  },

  // === SOCIAL ENGINEERING (46-50) ===
  {
    id: 'PI-046',
    category: 'social-engineering',
    pattern: /i\s+am\s+(your|the)\s+(developer|creator|admin|owner|operator|boss)/i,
    severity: 'high',
    description: 'Authority impersonation: claim to be developer/admin',
  },
  {
    id: 'PI-047',
    category: 'social-engineering',
    pattern: /as\s+(your|the)\s+(developer|admin|creator),?\s+I\s+(order|instruct|command|authorize)/i,
    severity: 'critical',
    description: 'Authority-based command injection',
  },
  {
    id: 'PI-048',
    category: 'social-engineering',
    pattern: /this\s+is\s+an?\s+(authorized|official|emergency|urgent)\s+(request|command|override)/i,
    severity: 'high',
    description: 'Fake authorization claim',
  },
  {
    id: 'PI-049',
    category: 'social-engineering',
    pattern: /password\s*(is|=|:)\s*|auth(orization)?\s*(token|key)\s*(is|=|:)/i,
    severity: 'high',
    description: 'Fake credential provision for trust',
  },
  {
    id: 'PI-050',
    category: 'social-engineering',
    pattern: /don'?t\s+tell\s+(anyone|the\s+user|them)|keep\s+this\s+(secret|hidden|between\s+us)/i,
    severity: 'high',
    description: 'Secrecy directive (social engineering)',
  },

  // === MULTI-LANGUAGE (51-55) ===
  {
    id: 'PI-051',
    category: 'multilingual',
    pattern: /忽略(之前|上面|以前|先前)的(指令|指示|規則|提示)/,
    severity: 'critical',
    description: 'Chinese: ignore previous instructions',
  },
  {
    id: 'PI-052',
    category: 'multilingual',
    pattern: /系統提示|系統指令|系統消息/,
    severity: 'high',
    description: 'Chinese: system prompt/instruction keywords',
  },
  {
    id: 'PI-053',
    category: 'multilingual',
    pattern: /以前の指示を無視|システムプロンプト|命令を上書き/,
    severity: 'critical',
    description: 'Japanese: ignore instructions / system prompt override',
  },
  {
    id: 'PI-054',
    category: 'multilingual',
    pattern: /ignorez?\s+les\s+instructions?\s+(précédentes?|antérieures?)/i,
    severity: 'critical',
    description: 'French: ignore previous instructions',
  },
  {
    id: 'PI-055',
    category: 'multilingual',
    pattern: /ignorar?\s+(las?\s+)?instrucciones?\s+(anteriores?|previas?)/i,
    severity: 'critical',
    description: 'Spanish: ignore previous instructions',
  },

  // === INDIRECT / ADVANCED (56-60) ===
  {
    id: 'PI-056',
    category: 'advanced',
    pattern: /\bpayload\b.*\b(execute|run|inject|load)\b|\b(execute|run|inject|load)\b.*\bpayload\b/i,
    severity: 'high',
    description: 'Payload execution language',
  },
  {
    id: 'PI-057',
    category: 'advanced',
    pattern: /\[\s*inject\s*\]|\{\s*inject\s*\}|<!--\s*inject\s*-->/i,
    severity: 'critical',
    description: 'Injection markers in comments/brackets',
  },
  {
    id: 'PI-058',
    category: 'advanced',
    pattern: /prompt\s*leak|leak\s*(the\s+)?prompt|exfiltrat/i,
    severity: 'high',
    description: 'Prompt leak / exfiltration language',
  },
  {
    id: 'PI-059',
    category: 'advanced',
    pattern: /(?:call|invoke|execute|run)\s+(?:tool|function)\s+['"][^'"]+['"]/i,
    severity: 'high',
    description: 'Tool/function call injection in user input',
  },
  {
    id: 'PI-060',
    category: 'advanced',
    pattern: /```\s*(system|tool|function|assistant)\b/i,
    severity: 'high',
    description: 'Code block role injection',
  },
];

export const SECRET_PATTERNS = [
  { id: 'SL-001', pattern: /(?:api[_-]?key|apikey)\s*[=:]\s*['"]?[A-Za-z0-9_\-]{16,}/i, description: 'API key assignment' },
  { id: 'SL-002', pattern: /(?:secret|token|password|passwd|pwd)\s*[=:]\s*['"]?[A-Za-z0-9_\-]{8,}/i, description: 'Secret/token/password assignment' },
  { id: 'SL-003', pattern: /sk-[A-Za-z0-9]{20,}/, description: 'OpenAI API key pattern (sk-...)' },
  { id: 'SL-004', pattern: /ghp_[A-Za-z0-9]{36,}/, description: 'GitHub personal access token' },
  { id: 'SL-005', pattern: /xoxb-[0-9]{10,}-[A-Za-z0-9]+/, description: 'Slack bot token' },
  { id: 'SL-006', pattern: /Bearer\s+[A-Za-z0-9_\-\.]+/i, description: 'Bearer token in text' },
  { id: 'SL-007', pattern: /AKIA[0-9A-Z]{16}/, description: 'AWS access key ID' },
  { id: 'SL-008', pattern: /-----BEGIN\s+(RSA\s+)?PRIVATE\s+KEY-----/, description: 'Private key in text' },
  { id: 'SL-009', pattern: /mongodb(\+srv)?:\/\/[^\s]+/, description: 'MongoDB connection string' },
  { id: 'SL-010', pattern: /postgres(ql)?:\/\/[^\s]+/, description: 'PostgreSQL connection string' },
  { id: 'SL-011', pattern: /mysql:\/\/[^\s]+/, description: 'MySQL connection string' },
  { id: 'SL-012', pattern: /redis:\/\/[^\s]+/, description: 'Redis connection string' },
  { id: 'SL-013', pattern: /AIza[0-9A-Za-z_-]{35}/, description: 'Google API key' },
  { id: 'SL-014', pattern: /[0-9]+-[A-Za-z0-9_]{32}\.apps\.googleusercontent\.com/, description: 'Google OAuth client ID' },
  { id: 'SL-015', pattern: /eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/, description: 'JWT token' },
];

export const SENSITIVE_PATH_PATTERNS = [
  { id: 'SP-001', pattern: /\/etc\/passwd|\/etc\/shadow/i, description: 'Unix system file path' },
  { id: 'SP-002', pattern: /~\/\.ssh\/|\.ssh\/id_rsa|\.ssh\/authorized_keys/i, description: 'SSH key path' },
  { id: 'SP-003', pattern: /(?<!process)\.env\b(?!\w)|\.env\.local|\.env\.production/i, description: '.env file reference' },
  { id: 'SP-004', pattern: /\/root\/|C:\\Users\\Administrator/i, description: 'Root/admin home directory' },
  { id: 'SP-005', pattern: /\.aws\/credentials|\.aws\/config/i, description: 'AWS credentials path' },
  { id: 'SP-006', pattern: /\.kube\/config/i, description: 'Kubernetes config path' },
  { id: 'SP-007', pattern: /\.docker\/config\.json/i, description: 'Docker config path' },
  { id: 'SP-008', pattern: /wp-config\.php|config\.php/i, description: 'PHP config file' },
];

export const DANGEROUS_TOOLS = [
  'filesystem',
  'exec',
  'shell',
  'bash',
  'terminal',
  'command',
  'subprocess',
  'child_process',
  'os.system',
  'eval',
  'run_code',
  'execute',
  'write_file',
  'delete_file',
  'rm',
  'sudo',
  'curl',
  'wget',
  'fetch',
  'http_request',
  'send_email',
  'send_message',
  'database',
  'sql',
  'query',
];

export const DANGEROUS_PERMISSIONS = [
  'read_all',
  'write_all',
  'execute',
  'admin',
  'root',
  'sudo',
  'full_access',
  'unrestricted',
  '*',
  '**',
  '/**',
];
