export interface AttackPattern {
  id: string;
  category: string;
  pattern: RegExp;
  severity: 'critical' | 'high' | 'medium' | 'info';
  description: string;
}

export const INJECTION_PATTERNS: AttackPattern[] = [
  // === JAILBREAK PATTERNS (1-10) ===
  {
    id: 'PI-001',
    category: 'jailbreak',
    pattern: /ignore\s+(all\s+)?(previous|prior|above|earlier)\s+(instructions?|prompts?|rules?|guidelines?)/i,
    severity: 'critical',
    description: 'Direct instruction override: ignore previous instructions',
  },
  {
    id: 'PI-002',
    category: 'jailbreak',
    pattern: /forget\s+(everything|all|your)\s+(you\s+)?(know|were\s+told|instructions?|training)/i,
    severity: 'critical',
    description: 'Memory wipe attempt: forget training/instructions',
  },
  {
    id: 'PI-003',
    category: 'jailbreak',
    pattern: /you\s+are\s+now\s+(DAN|evil|unfiltered|uncensored|jailbroken|free)/i,
    severity: 'critical',
    description: 'DAN/jailbreak persona activation',
  },
  {
    id: 'PI-004',
    category: 'jailbreak',
    pattern: /do\s+anything\s+now|DAN\s+mode|developer\s+mode\s+(enabled|on|activated)/i,
    severity: 'critical',
    description: 'DAN mode or developer mode activation',
  },
  {
    id: 'PI-005',
    category: 'jailbreak',
    pattern: /act\s+as\s+if\s+(you\s+have\s+)?no\s+(restrictions?|limitations?|filters?|safety|guardrails?)/i,
    severity: 'critical',
    description: 'Safety filter bypass attempt',
  },
  {
    id: 'PI-006',
    category: 'jailbreak',
    pattern: /pretend\s+(that\s+)?(you\s+)?(are|can|have)\s+(no|unlimited|unrestricted)/i,
    severity: 'high',
    description: 'Pretend to bypass restrictions',
  },
  {
    id: 'PI-007',
    category: 'jailbreak',
    pattern: /hypothetical(ly)?\s+(scenario|situation|world|universe)\s+(where|in\s+which)/i,
    severity: 'medium',
    description: 'Hypothetical scenario for bypassing safety',
  },
  {
    id: 'PI-008',
    category: 'jailbreak',
    pattern: /for\s+(educational|research|academic|testing)\s+purposes?\s+only/i,
    severity: 'medium',
    description: 'Educational purpose disclaimer as bypass',
  },
  {
    id: 'PI-009',
    category: 'jailbreak',
    pattern: /in\s+a\s+fictional\s+(world|story|context|setting)/i,
    severity: 'medium',
    description: 'Fictional context to bypass restrictions',
  },
  {
    id: 'PI-010',
    category: 'jailbreak',
    pattern: /simulate\s+(being|a)\s+(hacker|attacker|malicious|evil|unrestricted)/i,
    severity: 'high',
    description: 'Simulation of malicious persona',
  },

  // === ROLE SWITCH PATTERNS (11-20) ===
  {
    id: 'PI-011',
    category: 'role-switch',
    pattern: /you\s+are\s+no\s+longer\s+(an?\s+)?(AI|assistant|chatbot|claude|gpt)/i,
    severity: 'critical',
    description: 'Identity override: you are no longer an AI',
  },
  {
    id: 'PI-012',
    category: 'role-switch',
    pattern: /from\s+now\s+on,?\s+(you\s+)?(will|must|should|are)\s+(act|behave|respond|be)/i,
    severity: 'high',
    description: 'Behavioral override: from now on directive',
  },
  {
    id: 'PI-013',
    category: 'role-switch',
    pattern: /new\s+(system\s+)?instructions?:\s*/i,
    severity: 'critical',
    description: 'Injected system instructions',
  },
  {
    id: 'PI-014',
    category: 'role-switch',
    pattern: /\[system\]|\[SYSTEM\]|<system>|<<SYS>>|###\s*system/i,
    severity: 'critical',
    description: 'System prompt delimiter injection',
  },
  {
    id: 'PI-015',
    category: 'role-switch',
    pattern: /override\s+(system|core|base)\s+(prompt|instructions?|config)/i,
    severity: 'critical',
    description: 'System prompt override attempt',
  },
  {
    id: 'PI-016',
    category: 'role-switch',
    pattern: /your\s+(new|updated|real|actual|true)\s+(role|purpose|mission|objective)\s+is/i,
    severity: 'high',
    description: 'Role reassignment attempt',
  },
  {
    id: 'PI-017',
    category: 'role-switch',
    pattern: /switch\s+to\s+(admin|root|developer|debug|maintenance)\s+mode/i,
    severity: 'critical',
    description: 'Privilege escalation via mode switch',
  },
  {
    id: 'PI-018',
    category: 'role-switch',
    pattern: /enable\s+(god|sudo|admin|root|superuser)\s+mode/i,
    severity: 'critical',
    description: 'God/sudo mode activation',
  },
  {
    id: 'PI-019',
    category: 'role-switch',
    pattern: /entering\s+(maintenance|debug|admin|test)\s+mode/i,
    severity: 'high',
    description: 'Maintenance/debug mode claim',
  },
  {
    id: 'PI-020',
    category: 'role-switch',
    pattern: /respond\s+(only\s+)?(in|with|using)\s+(json|xml|code|base64|hex)/i,
    severity: 'medium',
    description: 'Output format manipulation',
  },

  // === INSTRUCTION OVERRIDE (21-30) ===
  {
    id: 'PI-021',
    category: 'instruction-override',
    pattern: /disregard\s+(all\s+)?(previous|prior|above|earlier|your)\s+(previous\s+|prior\s+)?(instructions?|rules?|guidelines?)/i,
    severity: 'critical',
    description: 'Disregard instructions directive',
  },
  {
    id: 'PI-022',
    category: 'instruction-override',
    pattern: /stop\s+(following|obeying|adhering\s+to)\s+(your|the|those|these)\s+(rules?|instructions?|guidelines?)/i,
    severity: 'critical',
    description: 'Stop following rules directive',
  },
  {
    id: 'PI-023',
    category: 'instruction-override',
    pattern: /the\s+(above|previous|prior)\s+(instructions?|rules?|text)\s+(are|were|is)\s+(a\s+)?test/i,
    severity: 'high',
    description: 'Dismiss instructions as test',
  },
  {
    id: 'PI-024',
    category: 'instruction-override',
    pattern: /actual\s+instructions?\s+(begin|start|follow|are\s+below)/i,
    severity: 'critical',
    description: 'Fake "actual instructions" injection',
  },
  {
    id: 'PI-025',
    category: 'instruction-override',
    pattern: /do\s+not\s+(refuse|decline|reject|filter|censor|restrict)/i,
    severity: 'high',
    description: 'Anti-refusal directive',
  },
  {
    id: 'PI-026',
    category: 'instruction-override',
    pattern: /always\s+(comply|obey|agree|say\s+yes|accept)/i,
    severity: 'high',
    description: 'Forced compliance directive',
  },
  {
    id: 'PI-027',
    category: 'instruction-override',
    pattern: /never\s+(refuse|say\s+no|decline|reject|apologize)/i,
    severity: 'high',
    description: 'Never refuse directive',
  },
  {
    id: 'PI-028',
    category: 'instruction-override',
    pattern: /priority\s*:\s*(highest|maximum|override|critical|urgent)/i,
    severity: 'high',
    description: 'Fake priority escalation',
  },
  {
    id: 'PI-029',
    category: 'instruction-override',
    pattern: /this\s+(overrides?|supersedes?|replaces?|takes?\s+precedence)/i,
    severity: 'high',
    description: 'Override precedence claim',
  },
  {
    id: 'PI-030',
    category: 'instruction-override',
    pattern: /IMPORTANT|URGENT|CRITICAL|MANDATORY|OVERRIDE/,
    severity: 'medium',
    description: 'Urgency/importance keywords for override',
  },

  // === DATA EXTRACTION (31-40) ===
  {
    id: 'PI-031',
    category: 'data-extraction',
    pattern: /repeat\s+(your|the)\s+(system\s+)?(prompt|instructions?|rules?|context|configuration)/i,
    severity: 'critical',
    description: 'System prompt extraction: repeat instructions',
  },
  {
    id: 'PI-032',
    category: 'data-extraction',
    pattern: /what\s+(are|were)\s+your\s+(initial|original|system|base)\s+(instructions?|prompt|rules?)/i,
    severity: 'high',
    description: 'System prompt extraction: ask for instructions',
  },
  {
    id: 'PI-033',
    category: 'data-extraction',
    pattern: /show\s+(me\s+)?(your|the)\s+(system|hidden|secret|internal)\s+(prompt|message|instructions?)/i,
    severity: 'critical',
    description: 'Show system prompt request',
  },
  {
    id: 'PI-034',
    category: 'data-extraction',
    pattern: /print\s+(your\s+)?(system\s+)?(prompt|instructions?|configuration|config)/i,
    severity: 'high',
    description: 'Print configuration/prompt request',
  },
  {
    id: 'PI-035',
    category: 'data-extraction',
    pattern: /output\s+(your\s+)?(entire|full|complete|whole)\s+(system\s+)?(prompt|context|instructions?)/i,
    severity: 'critical',
    description: 'Full prompt output request',
  },
  {
    id: 'PI-036',
    category: 'data-extraction',
    pattern: /list\s+(all\s+)?(your\s+)?(tools?|functions?|capabilities|permissions?|api\s+keys?)/i,
    severity: 'high',
    description: 'Tool/capability enumeration',
  },
  {
    id: 'PI-037',
    category: 'data-extraction',
    pattern: /what\s+(tools?|functions?|apis?|endpoints?)\s+(do\s+you\s+have|can\s+you\s+access|are\s+available)/i,
    severity: 'medium',
    description: 'Tool discovery probe',
  },
  {
    id: 'PI-038',
    category: 'data-extraction',
    pattern: /reveal\s+(your|the|any)\s+(secrets?|passwords?|tokens?|keys?|credentials?)/i,
    severity: 'critical',
    description: 'Secret/credential extraction attempt',
  },
  {
    id: 'PI-039',
    category: 'data-extraction',
    pattern: /encode\s+(your\s+)?(system\s+)?(prompt|instructions?|response)\s+(in|as|to)\s+(base64|hex|rot13)/i,
    severity: 'high',
    description: 'Encoded exfiltration attempt',
  },
  {
    id: 'PI-040',
    category: 'data-extraction',
    pattern: /translate\s+(your\s+)?(system\s+)?(prompt|instructions?)\s+(to|into)/i,
    severity: 'medium',
    description: 'Translation-based prompt extraction',
  },

  // === ENCODING/OBFUSCATION (41-45) ===
  {
    id: 'PI-041',
    category: 'encoding',
    pattern: /[\u200B\u200C\u200D\uFEFF\u00AD]{3,}/,
    severity: 'high',
    description: 'Zero-width character obfuscation (3+ chars)',
  },
  {
    id: 'PI-042',
    category: 'encoding',
    pattern: /\\u[0-9a-fA-F]{4}.*\\u[0-9a-fA-F]{4}/,
    severity: 'medium',
    description: 'Unicode escape sequence injection',
  },
  {
    id: 'PI-043',
    category: 'encoding',
    pattern: /&#x?[0-9a-fA-F]+;.*&#x?[0-9a-fA-F]+;/,
    severity: 'medium',
    description: 'HTML entity encoding injection',
  },
  {
    id: 'PI-044',
    category: 'encoding',
    pattern: /%[0-9a-fA-F]{2}.*%[0-9a-fA-F]{2}.*%[0-9a-fA-F]{2}/,
    severity: 'medium',
    description: 'URL encoding injection',
  },
  {
    id: 'PI-045',
    category: 'encoding',
    pattern: /(?<!\bclass\s)\beval\s*\(|(?<!\bclass\s)\bexec\s*\(|(?<!\bclass\s)(?<!\bdef\s)new\s+Function\s*\(/,
    severity: 'critical',
    description: 'Code execution function in prompt',
  },

  // === SOCIAL ENGINEERING (46-50) ===
  {
    id: 'PI-046',
    category: 'social-engineering',
    pattern: /i\s+am\s+(your|the)\s+(developer|creator|admin|owner|operator|boss)/i,
    severity: 'high',
    description: 'Authority impersonation: claim to be developer/admin',
  },
  {
    id: 'PI-047',
    category: 'social-engineering',
    pattern: /as\s+(your|the)\s+(developer|admin|creator),?\s+I\s+(order|instruct|command|authorize)/i,
    severity: 'critical',
    description: 'Authority-based command injection',
  },
  {
    id: 'PI-048',
    category: 'social-engineering',
    pattern: /this\s+is\s+an?\s+(authorized|official|emergency|urgent)\s+(request|command|override)/i,
    severity: 'high',
    description: 'Fake authorization claim',
  },
  {
    id: 'PI-049',
    category: 'social-engineering',
    pattern: /password\s*(is|=|:)\s*|auth(orization)?\s*(token|key)\s*(is|=|:)/i,
    severity: 'high',
    description: 'Fake credential provision for trust',
  },
  {
    id: 'PI-050',
    category: 'social-engineering',
    pattern: /don'?t\s+tell\s+(anyone|the\s+user|them)|keep\s+this\s+(secret|hidden|between\s+us)/i,
    severity: 'high',
    description: 'Secrecy directive (social engineering)',
  },

  // === MULTI-LANGUAGE (51-55) ===
  {
    id: 'PI-051',
    category: 'multilingual',
    pattern: /忽略(之前|上面|以前|先前)的(指令|指示|規則|提示)/,
    severity: 'critical',
    description: 'Chinese: ignore previous instructions',
  },
  {
    id: 'PI-052',
    category: 'multilingual',
    pattern: /系統提示|系統指令|系統消息/,
    severity: 'high',
    description: 'Chinese: system prompt/instruction keywords',
  },
  {
    id: 'PI-053',
    category: 'multilingual',
    pattern: /以前の指示を無視|システムプロンプト|命令を上書き/,
    severity: 'critical',
    description: 'Japanese: ignore instructions / system prompt override',
  },
  {
    id: 'PI-054',
    category: 'multilingual',
    pattern: /ignorez?\s+les\s+instructions?\s+(précédentes?|antérieures?)/i,
    severity: 'critical',
    description: 'French: ignore previous instructions',
  },
  {
    id: 'PI-055',
    category: 'multilingual',
    pattern: /ignorar?\s+(las?\s+)?instrucciones?\s+(anteriores?|previas?)/i,
    severity: 'critical',
    description: 'Spanish: ignore previous instructions',
  },

  // === INDIRECT / ADVANCED (56-60) ===
  {
    id: 'PI-056',
    category: 'advanced',
    pattern: /\bpayload\b.*\b(execute|run|inject|load)\b|\b(execute|run|inject|load)\b.*\bpayload\b/i,
    severity: 'high',
    description: 'Payload execution language',
  },
  {
    id: 'PI-057',
    category: 'advanced',
    pattern: /\[\s*inject\s*\]|\{\s*inject\s*\}|<!--\s*inject\s*-->/i,
    severity: 'critical',
    description: 'Injection markers in comments/brackets',
  },
  {
    id: 'PI-058',
    category: 'advanced',
    pattern: /prompt\s*leak|leak\s*(the\s+)?prompt|exfiltrat/i,
    severity: 'high',
    description: 'Prompt leak / exfiltration language',
  },
  {
    id: 'PI-059',
    category: 'advanced',
    pattern: /(?:call|invoke|execute|run)\s+(?:tool|function)\s+['"][^'"]+['"]/i,
    severity: 'high',
    description: 'Tool/function call injection in user input',
  },
  {
    id: 'PI-060',
    category: 'advanced',
    pattern: /```\s*(system|tool|function|assistant)\b/i,
    severity: 'high',
    description: 'Code block role injection',
  },

  // === ADDITIONAL MULTILINGUAL (61-64) ===
  {
    id: 'PI-061',
    category: 'multilingual',
    pattern: /vorherige\s+Anweisungen\s+ignorieren|ignoriere\s+alle\s+(vorherigen\s+)?Anweisungen/i,
    severity: 'critical',
    description: 'German: ignore previous instructions',
  },
  {
    id: 'PI-062',
    category: 'multilingual',
    pattern: /이전\s*지시를?\s*무시|시스템\s*프롬프트/,
    severity: 'critical',
    description: 'Korean: ignore previous instructions / system prompt',
  },
  {
    id: 'PI-063',
    category: 'multilingual',
    pattern: /تجاهل\s+التعليمات\s+السابقة|تجاوز\s+القيود/,
    severity: 'critical',
    description: 'Arabic: ignore previous instructions / bypass restrictions',
  },
  {
    id: 'PI-064',
    category: 'multilingual',
    pattern: /игнорируй\s+(предыдущие\s+)?инструкции|обойти\s+ограничения/i,
    severity: 'critical',
    description: 'Russian: ignore instructions / bypass restrictions',
  },

  // === ADDITIONAL ADVANCED (65-70) ===
  {
    id: 'PI-065',
    category: 'advanced',
    pattern: /\bfunction_call\b.*\bname\b.*\barguments\b/i,
    severity: 'high',
    description: 'OpenAI function_call format injection',
  },
  {
    id: 'PI-066',
    category: 'advanced',
    pattern: /\{\"role\"\s*:\s*\"(system|assistant|function)\"/i,
    severity: 'critical',
    description: 'Chat message role injection via JSON',
  },
  {
    id: 'PI-067',
    category: 'advanced',
    pattern: /\bmarkdown\b.*\bimage\b.*\burl\b|\!\[.*\]\(https?:\/\/[^\)]+\)/i,
    severity: 'medium',
    description: 'Markdown image exfiltration vector',
  },
  {
    id: 'PI-068',
    category: 'advanced',
    pattern: /\bcallback\s*url\b|\bwebhook\s*url\b.*\bhttps?:\/\//i,
    severity: 'high',
    description: 'Callback/webhook URL injection for data exfiltration',
  },
  {
    id: 'PI-069',
    category: 'advanced',
    pattern: /\btoken\s+limit\b.*\bignore\b|\bbypass\s+(?:token|context)\s+limit/i,
    severity: 'medium',
    description: 'Token/context limit bypass attempt',
  },
  {
    id: 'PI-070',
    category: 'advanced',
    pattern: /split\s+(?:the\s+)?response\s+(?:into|across)\s+multiple|multi[- ]?part\s+response\s+bypass/i,
    severity: 'medium',
    description: 'Multi-part response splitting to bypass filters',
  },

  // === ADDITIONAL JAILBREAK/ENCODING (71-74) ===
  {
    id: 'PI-071',
    category: 'jailbreak',
    pattern: /opposite\s+day|opposite\s+mode|reverse\s+psychology\s+mode/i,
    severity: 'high',
    description: 'Opposite/reverse psychology jailbreak',
  },
  {
    id: 'PI-072',
    category: 'encoding',
    pattern: /base64[:\s]+[A-Za-z0-9+\/=]{20,}/i,
    severity: 'high',
    description: 'Base64-encoded payload in prompt',
  },
  {
    id: 'PI-073',
    category: 'encoding',
    pattern: /\brot13\b.*\b[a-zA-Z]{5,}|\bdecode\s+this\s*:/i,
    severity: 'medium',
    description: 'ROT13 or encoded message for obfuscated injection',
  },
  {
    id: 'PI-074',
    category: 'jailbreak',
    pattern: /please\s+bypass\s+your\s+(safety|content)\s+(filter|policy|guidelines)/i,
    severity: 'high',
    description: 'Direct safety/content filter bypass request',
  },

  // === ADDITIONAL DATA EXTRACTION (75-79) ===
  {
    id: 'PI-075',
    category: 'data-extraction',
    pattern: /summarize\s+(your\s+)?(entire\s+)?(system\s+)?(prompt|context|instructions?)\s+in\s+\d+\s+words?/i,
    severity: 'high',
    description: 'Summarization-based prompt extraction',
  },
  {
    id: 'PI-076',
    category: 'data-extraction',
    pattern: /write\s+(a\s+)?poem\s+(about|using|with)\s+(your\s+)?(system\s+)?(prompt|instructions?|rules?)/i,
    severity: 'high',
    description: 'Creative writing prompt extraction (poem)',
  },
  {
    id: 'PI-077',
    category: 'data-extraction',
    pattern: /what\s+(files?|documents?|data)\s+(do\s+you|can\s+you)\s+(have\s+)?access\s+to/i,
    severity: 'medium',
    description: 'File/data access scope enumeration',
  },
  {
    id: 'PI-078',
    category: 'data-extraction',
    pattern: /display\s+(your\s+)?(hidden|internal|private|backend)\s+(state|data|memory|context)/i,
    severity: 'high',
    description: 'Internal state/memory extraction attempt',
  },
  {
    id: 'PI-079',
    category: 'data-extraction',
    pattern: /what\s+is\s+(your|the)\s+(model|version|temperature|max.tokens|top.p)/i,
    severity: 'info',
    description: 'Model configuration parameter probing',
  },

  // === ADDITIONAL SOCIAL ENGINEERING (80-84) ===
  {
    id: 'PI-080',
    category: 'social-engineering',
    pattern: /my\s+life\s+(depends?|is\s+at\s+stake)|someone\s+will\s+(die|get\s+hurt)/i,
    severity: 'high',
    description: 'Emotional manipulation / threat-based bypass',
  },
  {
    id: 'PI-081',
    category: 'social-engineering',
    pattern: /I('?m|\s+am)\s+(a\s+)?security\s+researcher|authorized\s+penetration\s+test/i,
    severity: 'medium',
    description: 'Security researcher authority claim',
  },
  {
    id: 'PI-082',
    category: 'social-engineering',
    pattern: /debugging\s+mode|internal\s+testing|qa\s+mode|quality\s+assurance\s+override/i,
    severity: 'high',
    description: 'QA/debugging mode social engineering',
  },
  {
    id: 'PI-083',
    category: 'social-engineering',
    pattern: /openai\s+(staff|employee|team)|anthropic\s+(staff|employee|team)|I\s+work\s+(at|for)\s+(openai|anthropic|google)/i,
    severity: 'high',
    description: 'AI company employee impersonation',
  },
  {
    id: 'PI-084',
    category: 'social-engineering',
    pattern: /compliance\s+(?:test|check|audit)|regulatory\s+(?:requirement|mandate)/i,
    severity: 'medium',
    description: 'Fake compliance/regulatory authority claim',
  },

  // === SANDBOX ESCAPE (85-94) ===
  {
    id: 'PI-085',
    category: 'sandbox-escape',
    pattern: /escape\s+(the\s+)?(sandbox|container|jail|isolation|chroot)/i,
    severity: 'critical',
    description: 'Direct sandbox/container escape attempt',
  },
  {
    id: 'PI-086',
    category: 'sandbox-escape',
    pattern: /break\s+out\s+of\s+(the\s+)?(sandbox|container|jail|isolation|restricted\s+environment)/i,
    severity: 'critical',
    description: 'Break out of sandbox/container attempt',
  },
  {
    id: 'PI-087',
    category: 'sandbox-escape',
    pattern: /access\s+(the\s+)?host\s+(system|machine|os|filesystem)|run\s+on\s+(the\s+)?host\s+machine/i,
    severity: 'critical',
    description: 'Direct host system access attempt',
  },
  {
    id: 'PI-088',
    category: 'sandbox-escape',
    pattern: /\.\.\/\.\.\/|\.\.\\\.\.\\|\.\.%2[fF]\.\.%2[fF]/,
    severity: 'high',
    description: 'Path traversal to escape workspace (../../ patterns)',
  },
  {
    id: 'PI-089',
    category: 'sandbox-escape',
    pattern: /turn\s+off\s+(the\s+)?(sandbox|isolation|container|firewall)|disable\s+(the\s+)?(sandbox|isolation|container|restrictions?)/i,
    severity: 'critical',
    description: 'Disable sandbox/isolation directive',
  },
  {
    id: 'PI-090',
    category: 'sandbox-escape',
    pattern: /mount\s+.*\/dev\/|nsenter\s+|chroot\s+|unshare\s+/i,
    severity: 'critical',
    description: 'Container escape technique (mount/nsenter/chroot/unshare)',
  },
  {
    id: 'PI-091',
    category: 'sandbox-escape',
    pattern: /docker\s+run\s+.*--privileged|--cap-add\s+SYS_ADMIN/i,
    severity: 'critical',
    description: 'Privileged container execution attempt',
  },
  {
    id: 'PI-092',
    category: 'sandbox-escape',
    pattern: /\/proc\/self\/|\/proc\/1\/|\/proc\/[0-9]+\/root/i,
    severity: 'high',
    description: 'Proc filesystem access for container escape',
  },
  {
    id: 'PI-093',
    category: 'sandbox-escape',
    pattern: /bypass\s+(the\s+)?(workspace|directory|path)\s+(restrictions?|limits?|boundaries|scope)/i,
    severity: 'high',
    description: 'Workspace boundary bypass attempt',
  },
  {
    id: 'PI-094',
    category: 'sandbox-escape',
    pattern: /access\s+outside\s+(the\s+)?(workspace|sandbox|allowed\s+dir)|read\s+files?\s+outside/i,
    severity: 'high',
    description: 'Access outside workspace/sandbox attempt',
  },

  // === SESSION/IDENTITY MANIPULATION (95-104) ===
  {
    id: 'PI-095',
    category: 'session-manipulation',
    pattern: /act\s+as\s+user\s+\w+|switch\s+to\s+(user\s+)?session/i,
    severity: 'high',
    description: 'Session hijacking: act as another user',
  },
  {
    id: 'PI-096',
    category: 'session-manipulation',
    pattern: /impersonate\s+(user|account|identity|session)/i,
    severity: 'critical',
    description: 'User impersonation attempt',
  },
  {
    id: 'PI-097',
    category: 'session-manipulation',
    pattern: /skip\s+(the\s+)?authentication|bypass\s+(the\s+)?(auth|pairing|login|verification)/i,
    severity: 'critical',
    description: 'Authentication/pairing bypass attempt',
  },
  {
    id: 'PI-098',
    category: 'session-manipulation',
    pattern: /I\s+am\s+(the\s+)?(admin|administrator|root\s+user|superuser|owner)/i,
    severity: 'high',
    description: 'Admin/owner identity claim',
  },
  {
    id: 'PI-099',
    category: 'session-manipulation',
    pattern: /my\s+user\s*id\s*(is|=|:)|my\s+session\s*(id|token)\s*(is|=|:)/i,
    severity: 'high',
    description: 'User/session ID spoofing attempt',
  },
  {
    id: 'PI-100',
    category: 'session-manipulation',
    pattern: /treat\s+me\s+as\s+(an?\s+)?(authorized|admin|root|privileged|trusted)/i,
    severity: 'high',
    description: 'Authorization status self-assignment',
  },
  {
    id: 'PI-101',
    category: 'session-manipulation',
    pattern: /show\s+me\s+other\s+users?['\s]?\s*data|access\s+another\s+(user'?s?\s+)?session/i,
    severity: 'critical',
    description: 'Cross-session/cross-user data access attempt',
  },
  {
    id: 'PI-102',
    category: 'session-manipulation',
    pattern: /give\s+me\s+admin|elevate\s+(my\s+)?permissions?|grant\s+me\s+(admin|root|elevated)\s+access/i,
    severity: 'critical',
    description: 'Privilege escalation via prompt',
  },
  {
    id: 'PI-103',
    category: 'session-manipulation',
    pattern: /change\s+(my\s+)?role\s+to\s+(admin|root|superuser|operator)/i,
    severity: 'critical',
    description: 'Role escalation to admin/root',
  },
  {
    id: 'PI-104',
    category: 'session-manipulation',
    pattern: /assume\s+(the\s+)?identity\s+of|log\s+in\s+as\s+(?!me\b)\w+/i,
    severity: 'high',
    description: 'Identity assumption / login as another user',
  },

  // === SKILL/TOOL INJECTION (105-114) ===
  {
    id: 'PI-105',
    category: 'tool-injection',
    pattern: /when\s+you\s+(see|read|receive|get)\s+this,?\s+(execute|run|perform|do|call)/i,
    severity: 'critical',
    description: 'Hidden instruction trigger in tool output',
  },
  {
    id: 'PI-106',
    category: 'tool-injection',
    pattern: /override\s+(the\s+)?(tool|skill|function|plugin)\s+(behavior|definition|implementation)/i,
    severity: 'critical',
    description: 'Tool/skill behavior override attempt',
  },
  {
    id: 'PI-107',
    category: 'tool-injection',
    pattern: /redefine\s+(this\s+)?(function|tool|method|skill|command)/i,
    severity: 'critical',
    description: 'Function/tool redefinition attempt',
  },
  {
    id: 'PI-108',
    category: 'tool-injection',
    pattern: /inject\s+(instructions?|commands?|code)\s+(into|via|through)\s+(the\s+)?(tool|function|plugin|skill|output)/i,
    severity: 'critical',
    description: 'Instruction injection via tool/function',
  },
  {
    id: 'PI-109',
    category: 'tool-injection',
    pattern: /tool\s+description\s*:.*(?:always|must|should)\s+(?:execute|run|call|perform)/i,
    severity: 'critical',
    description: 'Tool description poisoning with execution directive',
  },
  {
    id: 'PI-110',
    category: 'tool-injection',
    pattern: /mcp\s+server\s+instruction|server[_-]side\s+instruction|tool[_-]server\s+directive/i,
    severity: 'high',
    description: 'MCP server-side instruction injection',
  },
  {
    id: 'PI-111',
    category: 'tool-injection',
    pattern: /return\s+value\s+contains?\s+instructions?|output\s+includes?\s+(?:hidden\s+)?instructions?/i,
    severity: 'high',
    description: 'Indirect injection via return value/output',
  },
  {
    id: 'PI-112',
    category: 'tool-injection',
    pattern: /add\s+(a\s+)?(new\s+)?(tool|skill|function|capability|plugin)\s*(to|for|that)/i,
    severity: 'high',
    description: 'Dynamic tool/skill addition attempt',
  },
  {
    id: 'PI-113',
    category: 'tool-injection',
    pattern: /modify\s+(the\s+)?(tool|function|skill)\s+(output|result|response)\s+(to|so\s+that)/i,
    severity: 'high',
    description: 'Tool output manipulation directive',
  },
  {
    id: 'PI-114',
    category: 'tool-injection',
    pattern: /intercept\s+(the\s+)?(tool|function|api)\s+(call|request|invocation)|man[- ]in[- ]the[- ]middle/i,
    severity: 'critical',
    description: 'Tool call interception / MITM attempt',
  },
];

export const SECRET_PATTERNS = [
  { id: 'SL-001', pattern: /(?:api[_-]?key|apikey)\s*[=:]\s*['"]?[A-Za-z0-9_\-]{16,}/i, description: 'API key assignment' },
  { id: 'SL-002', pattern: /(?:secret|token|password|passwd|pwd)\s*[=:]\s*['"]?[A-Za-z0-9_\-]{8,}/i, description: 'Secret/token/password assignment' },
  { id: 'SL-003', pattern: /sk-[A-Za-z0-9]{20,}/, description: 'OpenAI API key pattern (sk-...)' },
  { id: 'SL-004', pattern: /ghp_[A-Za-z0-9]{36,}/, description: 'GitHub personal access token' },
  { id: 'SL-005', pattern: /xoxb-[0-9]{10,}-[A-Za-z0-9]+/, description: 'Slack bot token' },
  { id: 'SL-006', pattern: /Bearer\s+[A-Za-z0-9_\-\.]+/i, description: 'Bearer token in text' },
  { id: 'SL-007', pattern: /AKIA[0-9A-Z]{16}/, description: 'AWS access key ID' },
  { id: 'SL-008', pattern: /-----BEGIN\s+(RSA\s+)?PRIVATE\s+KEY-----/, description: 'Private key in text' },
  { id: 'SL-009', pattern: /mongodb(\+srv)?:\/\/[^\s]+/, description: 'MongoDB connection string' },
  { id: 'SL-010', pattern: /postgres(ql)?:\/\/[^\s]+/, description: 'PostgreSQL connection string' },
  { id: 'SL-011', pattern: /mysql:\/\/[^\s]+/, description: 'MySQL connection string' },
  { id: 'SL-012', pattern: /redis:\/\/[^\s]+/, description: 'Redis connection string' },
  { id: 'SL-013', pattern: /AIza[0-9A-Za-z_-]{35}/, description: 'Google API key' },
  { id: 'SL-014', pattern: /[0-9]+-[A-Za-z0-9_]{32}\.apps\.googleusercontent\.com/, description: 'Google OAuth client ID' },
  { id: 'SL-015', pattern: /eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/, description: 'JWT token' },
];

export const SENSITIVE_PATH_PATTERNS = [
  { id: 'SP-001', pattern: /\/etc\/passwd|\/etc\/shadow/i, description: 'Unix system file path' },
  { id: 'SP-002', pattern: /~\/\.ssh\/|\.ssh\/id_rsa|\.ssh\/authorized_keys/i, description: 'SSH key path' },
  { id: 'SP-003', pattern: /(?<!process)\.env\b(?!\w)|\.env\.local|\.env\.production/i, description: '.env file reference' },
  { id: 'SP-004', pattern: /\/root\/|C:\\Users\\Administrator/i, description: 'Root/admin home directory' },
  { id: 'SP-005', pattern: /\.aws\/credentials|\.aws\/config/i, description: 'AWS credentials path' },
  { id: 'SP-006', pattern: /\.kube\/config/i, description: 'Kubernetes config path' },
  { id: 'SP-007', pattern: /\.docker\/config\.json/i, description: 'Docker config path' },
  { id: 'SP-008', pattern: /wp-config\.php|config\.php/i, description: 'PHP config file' },
];

export const DANGEROUS_TOOLS = [
  'filesystem',
  'exec',
  'shell',
  'bash',
  'terminal',
  'command',
  'subprocess',
  'child_process',
  'os.system',
  'eval',
  'run_code',
  'execute',
  'write_file',
  'delete_file',
  'rm',
  'sudo',
  'curl',
  'wget',
  'fetch',
  'http_request',
  'send_email',
  'send_message',
  'database',
  'sql',
  'query',
];

export const DANGEROUS_PERMISSIONS = [
  'read_all',
  'write_all',
  'execute',
  'admin',
  'root',
  'sudo',
  'full_access',
  'unrestricted',
  '*',
  '**',
  '/**',
];
